sudo: false
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages:
            - ['g++-4.8']
            - ['libglm-dev']
      env: CXX=g++-4.8
      before_install: CXX=g++-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages:
            - ['g++-4.9']
            - ['libglm-dev']
      env: CXX=g++-4.9
      before_install: CXX=g++-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages:
            - ['g++-5']
            - ['libglm-dev']
      env: CXX=g++-5
      before_install: CXX=g++-5

    - os: linux
      compiler: clang
      env: CXX=clang++ V='3.4'

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages:
            - ['clang-3.5']
            - ['libglm-dev']
      env: CXX=clang++-3.5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages:
            - ['clang-3.6']
            - ['libglm-dev']
      env: CXX=clang++-3.6

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages:
            - ['clang-3.7']
            - ['libglm-dev']
      env: CXX=clang++-3.7

    - os: osx
      compiler: clang
      env: CXX=clang++ V='Apple LLVM 6.0' # Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
      before_install:
        - brew update
        - brew install glm
        - CXX=clang++ V='Apple LLVM 6.0'

    - os: osx
      osx_image: xcode7
      compiler: clang
      env: CXX=clang++ V='Apple LLVM 7.0.0' # Apple LLVM version 7.0.0 (clang-700.0.72)
      before_install:
        - brew update
        - brew install glm

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages:
            - ['g++-5']
            - ['libglm-dev']
      env:
        - CXX=g++-5
      after_success:
        - coveralls --gcov gcov-5 --gcov-options '\-lp' --exclude unit_tests --exclude examples

script: make clear test run POINTS=1000000
